version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

python:
  install:
    - requirements: MangroveDB-Tutorial/requirements.txt

sphinx:
  configuration: MangroveDB-Tutorial/source/conf.py